# Generated by Django 3.2.9 on 2021-11-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('suite', models.CharField(max_length=50, verbose_name='Аппартамент')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('zipcode', models.CharField(max_length=50, verbose_name='Почтовый индекс')),
                ('geo_lat', models.CharField(max_length=8, verbose_name='Гео ширина')),
                ('geo_lng', models.CharField(max_length=8, verbose_name='Гео долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('catchPhrase', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('bs', models.CharField(max_length=100, verbose_name='Сфера работы')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_id', models.IntegerField(unique=True, verbose_name='jsonId')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('username', models.CharField(max_length=20, verbose_name='Пользователь')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('website', models.CharField(max_length=25, verbose_name='Сайт')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.address', verbose_name='Адрес')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.company', verbose_name='Компания')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_id', models.IntegerField(unique=True, verbose_name='jsonId')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('body', models.CharField(max_length=1000, verbose_name='Пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.users', verbose_name='Пользователь')),
            ],
        ),
    ]
